version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - python --version
  build:
    commands:
      - echo In buildspec-cleanup.yml Build started on `date`
  post_build:
    commands:
      - echo In buildspec-cleanup.yml Build completed on `date`
artifacts:
  files:
    - '**/*'
