version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo install phase started on `date`
      - python --version
      - 'curl -O https://bootstrap.pypa.io/get-pip.py'
      - python3 get-pip.py
      - pip install --upgrade pip
      - pip3 install taskcat
      - pip3 install --upgrade taskcat
  build:
    commands:
      - echo Build phase started on `date`
      # - taskcat test run --no-delete
      # - taskcat test run -k
      - taskcat test run
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'