---
AWSTemplateFormatVersion: '2010-09-09'
Description: Create a Lambda Layer
Parameters:
  S3Bucket:
    Description: S3 bucket that holds Python MySQL Package zipfile
    Type: String
    Default: ceoa-lambda
  S3Key:
    Description: zipfile key for Python MySQL Package
    Type: String
    Default: pymysql.zip
Resources:
  MyLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.6
        - python3.9
        - python3.8
      Content:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key
      Description: My layer
      LayerName: my-layer
      LicenseInfo: MIT